# Generated by Django 5.2 on 2025-04-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("current_latitude", models.FloatField()),
                ("current_longitude", models.FloatField()),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
